### ISSUE TITLE
Limited Questions generation from long text using "e2e-qg" 

### ISSUE THREAD

**Issue by pradeep8500** [patil-suraj/question_generation#20]
I am using ""e2e-qg"" model for question generation but it provides only limited questions (nearly 5 questions).
I want more questions from long text ,how can I get.

**Comment by patil-suraj** [comment]
Hi @pradeep8500 , how long is your text ? The max input length for T5 is 512 tokens, text longer than that is truncated.
You can try to break your long text into paragraphs and feed individual paragraphs into the model.

also you play with generate parameters
```python3
generate_kwargs = {
            "max_length": 256,
            "num_beams": 4,
            "length_penalty": 1.5,
            "no_repeat_ngram_size": 3,
            "early_stopping": True,
        }
```
these are the default ones, you can pass these as keywords arguments. Be sure to pass all the arguments, because when you pass gen kw args default ones are not used.

Let me know if this helps you and if you have any other issues.

**Comment by pradeep8500** [comment]
Hi @patil-suraj , Thanks  you very much  for responding ,
By default it accept only 256 tokens  but we can extended to 512 tokens right.
where can I pass these keyword arguments in  nlp= pipeline('e2e-qg') and also apply same technique to  "question-generation" pipeline getting questions answers for long text (nearly 5000 tokens)

**Comment by patil-suraj** [comment]
@pradeep8500 , max input length is 512. 256 here is the max output length passed to the `.generate` method.

To pass these arguments, just do 
```python3
generate_kwargs = {
    "max_length": 256,
    "num_beams": 4,
    "length_penalty": 1.5,
    "no_repeat_ngram_size": 3,
    "early_stopping": True,
}
nlp(text, **generate_kwargs)
```

`question-generation` pipeline doesn't accept these arguments. You should split your long text into smaller chunks and the pass each chunk to the pipeline.

Hope this answers your question.

**Comment by pradeep8500** [comment]
@patil-suraj , Thanks for sharing your valuable information.
Your code is so simple and wonderful .its helps a lot.
